# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'binding_of_caller'
gem 'activesupport'
gem 'pry'
gem 'parser'
gem 'unparser'
gem 'google-protobuf'
